# Copy config.example.yml and replace these values with accessible input paths.
# Run with: nextflow run main.nf -params-file config.yml -with-conda
input_csv: null
global_libraries: {}
raw_libraries: {}
conda_envs:
  mapping: null
  lr_assm: null
  sr_assm: null
outdir: results
pbs_queue: null
pbs_project: null
